

-- CREATE STUDENT TABLE
CREATE TABLE STUDENT
(
    STUDENT_ID VARCHAR(200) PRIMARY KEY NOT NULL,
    STUDENT_NAME VARCHAR(200),
    STUDENT_GENDER VARCHAR(10),
    STUDENT_BDATE DATE,
    STUDENT_CLASS VARCHAR(20),
    STUDENT_SECTION VARCHAR(20),
    CLASS_TEACHER VARCHAR(200),
    STUDENT_ADDRESS VARCHAR(500),
    GUARDIAN_NAME VARCHAR(200),
    GUARDIAN_EMAIL_ADDRESS VARCHAR(20),
    GURDIAN_CONTECT_NUMBER VARCHAR(20)
);


-- CREATE TEACHER TABLE
CREATE TABLE TEACHER
(
    TEACHER_ID VARCHAR(200) PRIMARY KEY NOT NULL,
    TEACHER_NAME VARCHAR(200),
    TEACHER_CONTACT_NUMBER VARCHAR(200),
    TEACHER_BDATE DATE,
    TEACHER_ADDRESS VARCHAR(500)
);

-- CREATE STUDENT_SUBJECT_DETAIL TABLE
CREATE TABLE STUDENT_SUBJECT_DETAIL
(
    STUDENT_ID VARCHAR(200),
	STUDENT_SUBJECT VARCHAR(200),
	TEACHER_ID VARCHAR(200),
	TEACHER_NAME VARCHAR(200)

);

CREATE TABLE SUBJECT
(
    SUBJECT_ID VARCHAR(200) PRIMARY KEY NOT NULL ,
	SUBJECT_NAME VARCHAR(200) UNIQUE

);

-- DROP TABLE

DROP TABLE STUDENT
 DROP TABLE TEACHER 
DROP TABLE STUDENT_SUBJECT_DETAIL
DROP TABLE SUBJECT